### ISSUE TITLE
主页帖子信息摘要字体颜色过浅

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#28]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/31304335/159121845-a088e0f6-bc75-4c76-bec8-ca383396eab1.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/31304335/159121865-ffb0af6f-05af-4568-8ff3-2dba80e9c85b.png">
<img width="849" alt="image" src="https://user-images.githubusercontent.com/31304335/159121873-b9596c34-4ff3-4619-afd4-00b084939eeb.png">

**Comment by jjaychen1e** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [主页帖子信息摘要字体颜色过浅](https://trello.com/c/SvXwgQGv/30-%E4%B8%BB%E9%A1%B5%E5%B8%96%E5%AD%90%E4%BF%A1%E6%81%AF%E6%91%98%E8%A6%81%E5%AD%97%E4%BD%93%E9%A2%9C%E8%89%B2%E8%BF%87%E6%B5%85)

**Comment by jjaychen1e** [comment]
Dark Mode

<img width="903" alt="image" src="https://user-images.githubusercontent.com/31304335/159123802-57918e07-d8b3-45b3-8b6f-5ea2bf41ab51.png">

**Comment by jjaychen1e** [comment]
不再修改两个 `public` 中的 `CSS` 文件。利用 `less` 的 `& when (@config-dark-mode = true)` 来适配两种颜色模式。
```less
/* https://github.com/ECNU-Forum/ECNU-Forum/issues/28 */
.read .DiscussionListItem-info .item-excerptM {
  & when (@config-dark-mode = true) {
    color: #999 !important;
  }
  & when (@config-dark-mode = false) {
    color: #888 !important;
  }
}

/* https://github.com/ECNU-Forum/ECNU-Forum/issues/28 */
.read .DiscussionListItem-main .DiscussionListItem-title {
  & when (@config-dark-mode = true) {
    color: #999 !important;
  }
  & when (@config-dark-mode = false) {
    color: #555 !important;
  }
}

/* https://github.com/ECNU-Forum/ECNU-Forum/issues/28 */
.unread .DiscussionListItem-info .item-excerptM {
  & when (@config-dark-mode = true) {
    color: #ddd !important;
  }
  & when (@config-dark-mode = false) {
    color: #666 !important;
  }
}
```
