### ISSUE TITLE
[BUG] 投票结果界面字体颜色未适配 Dark Mode

### ISSUE THREAD

**Issue by jjaychen1e** [ECNU-Forum/ECNU-Forum#63]
### 当前行为

<img width="552" alt="image" src="https://user-images.githubusercontent.com/31304335/160050438-873e0623-357d-441c-a017-094b2d821ab2.png">

### 预期行为

<img width="492" alt="image" src="https://user-images.githubusercontent.com/31304335/160050481-50052baa-c023-4298-aef5-ea64bbb17ca4.png">

### 平台信息

PC, Android, iOS, 其他

### 浏览器信息

Chrome, Firefox, Safari, Edge, 其他

### 用户状态信息

普通用户, 版主, 管理员

**Comment by jjaychen1e** [comment]
fix: 
```less
#modal > div > div > div > form > div.Modal-body > ul > div > h4 {
  & when (@config-dark-mode = true) {
    color: #fff !important;
  }
  & when (@config-dark-mode = false) {
    color: #000 !important;
  }
}
```
